name: Setup SurrealDB Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: SurrealDB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test Setup SurrealDB
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: Setup SurrealDB Action Test
    strategy:
      matrix:
        run-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.run-on }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Setup SurrealDB Action
        id: setup-surrealdb
        uses: ./
        with:
          version: latest

      - name: Print Output
        id: output
        run: echo "${{ steps.setup-surrealdb.outputs.surrealdb-version }}"

        # execute the surrealdb command that displays the version of the current surrealdb installation
      - name: Execute SurrealDB CLI
        run: surreal --version
